# Generated by Django 4.2.4 on 2023-09-29 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_follower_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(related_name='liker_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
