# Generated by Django 4.2.4 on 2023-09-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
