# Generated by Django 4.2.4 on 2023-09-29 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(blank=True, related_name='liker_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
