# Generated by Django 4.2.4 on 2023-10-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
