# Generated by Django 4.2.4 on 2023-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_alter_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
